spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    mode: HTML5
  profiles:
    active: pro
  messages:
    basename: i18n/messages


  mvc:
    static-path-pattern: /static/**
server:
  port: 8080
